// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:7b4fd9d2-290b-492b-a693-f9be88d503de",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_vtdbv7m5K",
    "aws_user_pools_web_client_id": "5kbp7gvchcluqaaudlqoa5d6k9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://idjvg3lllfbjjcciyqfq4unb2u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
